### ISSUE TITLE
Creating GUI for discord

### ISSUE THREAD

**Issue by johan123456718** [johan123456718/DiscordBot#14]
Try to fix a GUI in discord with emojis, window bars etc

**Comment by ghost** [comment]
# Approach 1:
- Create discord embed with
   - Game rules/ details
   - How to play
   - 3 emojis to represent Rock, Paper, and Scissors
- Create controller to read emoji selection and record it as player move
- Update game scoring system based on result of player move VS bot move
- Display results to user

**Comment by SiAust** [comment]
I am learning how to build an embed, I could probably make the GUI part of this, I can sketch out a design if you think that would be useful?

**Comment by johan123456718** [comment]
Hey SiAust.  

Sorry for late answer.

I have been busy. Sure, you can send me your sketch.
